# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: hello.proto for package 'helloworld'

require 'grpc'
require 'hello_pb'

module Helloworld
  module Greeter
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'helloworld.Greeter'

      rpc :SayHello, ::Helloworld::HelloRequest, ::Helloworld::HelloReply
      rpc :ListGreetings, ::Helloworld::HelloRequest, stream(::Helloworld::HelloReply)
      rpc :RecordNames, stream(::Helloworld::HelloRequest), ::Helloworld::HelloReply
      rpc :Chat, stream(::Helloworld::HelloRequest), stream(::Helloworld::HelloReply)
    end

    Stub = Service.rpc_stub_class
  end
end
